"""
GreenBookTranscription.py -- transcription of the Green Book for the Fidelity Assay
Amelia Interface Programme, Stage I

SOURCE
    Ccru, Writings 1997-2003 (Time Spiral Press / Urbanomic), supplied as a plain-text
    extraction (7,507 lines; SHA-256 of the extraction below). The extraction has no
    pagination, so every locator is a LINE NUMBER in that extraction plus the section
    name. Section names are edition-independent; page numbers can be added later.

CONTENT
    Data only. Nothing here is derived. Values are copied as printed, including
    printed values that disagree with the CCRU's own stated rules; FidelityAssay.py
    finds and reports those disagreements. Parenthetical demon aliases and titles
    are kept, but demon names are blinded (see demon_names()).

    MATRIX           all 45 entries of 'Pandemonium Matrix (Extracts from the
                     Lemurian Necronomicon)'. Rites are (Rt number, route, Mj/Mn label,
                     number of sub-rites). Route 'X' = syzygetic crossing; '?' = trackless.
    ZONE_NOTES       'The Zones', System Notes for Zones 0-9.
    GATE_NOTES       gate statements in the Zone system notes.
    SYSTEM           'Pandemonium: The system.'
    GLOSSARY_COUNTS  numerical statements in 'Appendix-1, Ccru Glossary'.
    DETAILED         the full entries for Lurgo (Mesh-00) and Katak (Mesh-14).
"""

SOURCE = {
    "title": "Ccru: Writings 1997-2003",
    "extraction_lines": 7507,
    "extraction_sha256": "97cdabd3e8a842c2500d4ff05a78bc8b25d99d9a52074c05a25f8066ce1d1d88",
    "matrix_section_lines": (5461, 5771),
    "zones_section_lines": (4549, 5459),
    "glossary_section_lines": (7020, 7374),
}

MATRIX = ({'mesh': 0,
  'net_span': (1, 0),
  'line': 5464,
  'phase_list_mesh': 0,
  'phase_list_line': 4792,
  'pitch': 'Ana-1',
  'class': 'Amphidemon',
  'clicks': (0,),
  'ciphers': (1, 10),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': True,
  'phase_limit': True,
  'decademon': None,
  'rites': ((1, '1890', None, 0),)},
 {'mesh': 1,
  'net_span': (2, 0),
  'line': 5471,
  'phase_list_mesh': 1,
  'phase_list_line': 4871,
  'pitch': 'Ana-2',
  'class': 'Amphidemon',
  'clicks': (1,),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': True,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '271890', None, 0), (2, '27541890', None, 1))},
 {'mesh': 2,
  'net_span': (2, 1),
  'line': 5478,
  'phase_list_mesh': 2,
  'phase_list_line': 4872,
  'pitch': 'Ana-3',
  'class': 'Cyclic Chronodemon',
  'clicks': (),
  'ciphers': (21,),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': ('Surge',),
  'door': False,
  'phase_limit': True,
  'decademon': None,
  'rites': ((1, '1872', 'Mn', 0), (2, '271', None, 0), (3, '27541', 'Mj', 1))},
 {'mesh': 3,
  'net_span': (3, 0),
  'line': 5487,
  'phase_list_mesh': 3,
  'phase_list_line': 4952,
  'pitch': 'Ana-3',
  'class': 'Chaotic Xenodemon',
  'clicks': (3,),
  'ciphers': (3,),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': True,
  'phase_limit': False,
  'decademon': None,
  'rites': ((0, '?', None, 0),)},
 {'mesh': 4,
  'net_span': (3, 1),
  'line': 5494,
  'phase_list_mesh': 4,
  'phase_list_line': 4953,
  'pitch': 'Ana-4',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '18723', None, 0), (2, '1872563', None, 1))},
 {'mesh': 5,
  'net_span': (3, 2),
  'line': 5500,
  'phase_list_mesh': 5,
  'phase_list_line': 4954,
  'pitch': 'Ana-5',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (3,),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': True,
  'decademon': None,
  'rites': ((1, '23', None, 0), (2, '27563', None, 1))},
 {'mesh': 6,
  'net_span': (4, 0),
  'line': 5508,
  'phase_list_mesh': 6,
  'phase_list_line': 5037,
  'pitch': 'Ana-4',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': True,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '41890', None, 1),)},
 {'mesh': 7,
  'net_span': (4, 1),
  'line': 5513,
  'phase_list_mesh': 7,
  'phase_list_line': 5038,
  'pitch': 'Ana-5',
  'class': 'Cyclic Chronodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (10,),
  'feeds': (),
  'prowls': ('Sink',),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '187254', 'Mn', 0), (2, '41', 'Mj', 1))},
 {'mesh': 8,
  'net_span': (4, 2),
  'line': 5521,
  'phase_list_mesh': 8,
  'phase_list_line': 5039,
  'pitch': 'Ana-6',
  'class': 'Cyclic Chronodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': ('Hold',),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '2754', 'Mn', 0), (2, '41872', None, 0), (3, '451872', 'Mj', 0))},
 {'mesh': 9,
  'net_span': (4, 3),
  'line': 5529,
  'phase_list_mesh': 9,
  'phase_list_line': 5040,
  'pitch': 'Ana-7',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': True,
  'decademon': None,
  'rites': ((1, '418723', None, 0), (2, '4518723', None, 0), (3, '4563', None, 1))},
 {'mesh': 10,
  'net_span': (5, 0),
  'line': 5538,
  'phase_list_mesh': 10,
  'phase_list_line': 5119,
  'pitch': 'Cth-4',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': True,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '541890', None, 1),)},
 {'mesh': 11,
  'net_span': (5, 1),
  'line': 5543,
  'phase_list_mesh': 11,
  'phase_list_line': 5120,
  'pitch': 'Cth-3',
  'class': 'Cyclic Chronodemon',
  'clicks': (),
  'ciphers': (15,),
  'haunts': (),
  'feeds': (),
  'prowls': ('Sink',),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '18725', 'Mn', 0), (2, '541', 'Mj', 1))},
 {'mesh': 12,
  'net_span': (5, 2),
  'line': 5551,
  'phase_list_mesh': 12,
  'phase_list_line': 5121,
  'pitch': 'Cth-2',
  'class': 'Cyclic Chronodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': ('Hold',),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '275', 'Mn', 0), (2, '541872', 'Mj', 1))},
 {'mesh': 13,
  'net_span': (5, 3),
  'line': 5558,
  'phase_list_mesh': 13,
  'phase_list_line': 5122,
  'pitch': 'Cth-1',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '5418723', None, 1), (2, '563', None, 1))},
 {'mesh': 14,
  'net_span': (5, 4),
  'line': 5565,
  'phase_list_mesh': 14,
  'phase_list_line': 5123,
  'pitch': 'Null',
  'class': 'Syzygetic Chronodemon',
  'clicks': (),
  'ciphers': (45,),
  'haunts': (),
  'feeds': ('Sink',),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': True,
  'decademon': None,
  'rites': ((0, 'X', None, 0), (1, '418725', None, 0))},
 {'mesh': 15,
  'net_span': (6, 0),
  'line': 5572,
  'phase_list_mesh': 15,
  'phase_list_line': 5198,
  'pitch': 'Cth-3',
  'class': 'Chaotic Xenodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': True,
  'phase_limit': False,
  'decademon': None,
  'rites': ((0, '?', None, 0),)},
 {'mesh': 16,
  'net_span': (6, 1),
  'line': 5578,
  'phase_list_mesh': 16,
  'phase_list_line': 5199,
  'pitch': 'Cth-2',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '187236', None, 1), (2, '187256', None, 0))},
 {'mesh': 17,
  'net_span': (6, 2),
  'line': 5584,
  'phase_list_mesh': 17,
  'phase_list_line': 5200,
  'pitch': 'Cth-2',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '236', None, 1), (2, '256', None, 0))},
 {'mesh': 18,
  'net_span': (6, 3),
  'line': 5591,
  'phase_list_mesh': 18,
  'phase_list_line': 5201,
  'pitch': 'Null',
  'class': 'Syzygetic Xenodemon',
  'clicks': (),
  'ciphers': (36,),
  'haunts': (6, 21),
  'feeds': ('Warp',),
  'prowls': ('Warp',),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((0, 'X', None, 2),)},
 {'mesh': 19,
  'net_span': (6, 4),
  'line': 5596,
  'phase_list_mesh': 19,
  'phase_list_line': 5202,
  'pitch': 'Ana-1',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': 1,
  'rites': ((1, '4187236', None, 1), (2, '45187236', None, 1), (3, '456', None, 0))},
 {'mesh': 20,
  'net_span': (6, 5),
  'line': 5604,
  'phase_list_mesh': 20,
  'phase_list_line': 5203,
  'pitch': 'Cth-7',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (15,),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': True,
  'decademon': None,
  'rites': ((1, '54187236', None, 2), (2, '56', None, 0))},
 {'mesh': 21,
  'net_span': (7, 0),
  'line': 5611,
  'phase_list_mesh': 21,
  'phase_list_line': 5278,
  'pitch': 'Cth-2',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': True,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '71890', None, 0), (2, '72541890', None, 1))},
 {'mesh': 22,
  'net_span': (7, 1),
  'line': 5619,
  'phase_list_mesh': 22,
  'phase_list_line': 5279,
  'pitch': 'Cth-1',
  'class': 'Cyclic Chronodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (28,),
  'feeds': (),
  'prowls': ('Surge',),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '187', 'Mn', 0), (2, '71', None, 0), (3, '72541', 'Mj', 0))},
 {'mesh': 23,
  'net_span': (7, 2),
  'line': 5627,
  'phase_list_mesh': 23,
  'phase_list_line': 5280,
  'pitch': 'Null',
  'class': 'Syzygetic Chronodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': ('Hold',),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((0, 'X', None, 0),)},
 {'mesh': 24,
  'net_span': (7, 3),
  'line': 5633,
  'phase_list_mesh': 24,
  'phase_list_line': 5281,
  'pitch': 'Ana-1',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': 2,
  'rites': ((1, '723', None, 0), (2, '72563', None, 1))},
 {'mesh': 25,
  'net_span': (7, 4),
  'line': 5639,
  'phase_list_mesh': 25,
  'phase_list_line': 5282,
  'pitch': 'Ana-2',
  'class': 'Cyclic Chronodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': ('Hold',),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '4187', None, 0), (2, '45187', 'Mn', 0), (3, '7254', 'Mj', 0))},
 {'mesh': 26,
  'net_span': (7, 5),
  'line': 5648,
  'phase_list_mesh': 26,
  'phase_list_line': 5283,
  'pitch': 'Cth-6',
  'class': 'Cyclic Chronodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': ('Hold',),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '54187', 'Mn', 1), (2, '725', 'Mj', 0))},
 {'mesh': 27,
  'net_span': (7, 6),
  'line': 5655,
  'phase_list_mesh': 27,
  'phase_list_line': 5284,
  'pitch': 'Cth-5',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': True,
  'decademon': None,
  'rites': ((1, '7236', None, 1), (2, '7256', None, 0))},
 {'mesh': 28,
  'net_span': (8, 0),
  'line': 5663,
  'phase_list_mesh': 28,
  'phase_list_line': 5360,
  'pitch': 'Cth-1',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': True,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '890', None, 0),)},
 {'mesh': 29,
  'net_span': (8, 1),
  'line': 5669,
  'phase_list_mesh': 29,
  'phase_list_line': 5361,
  'pitch': 'Null',
  'class': 'Syzygetic Chronodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': ('Surge',),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((0, 'X', None, 0),)},
 {'mesh': 30,
  'net_span': (8, 2),
  'line': 5675,
  'phase_list_mesh': 30,
  'phase_list_line': 5362,
  'pitch': 'Ana-1',
  'class': 'Cyclic Chronodemon',
  'clicks': (),
  'ciphers': (28,),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': ('Surge',),
  'door': False,
  'phase_limit': False,
  'decademon': 3,
  'rites': ((1, '2718', None, 0), (2, '275418', 'Mn', 1), (3, '8172', 'Mj', 0))},
 {'mesh': 31,
  'net_span': (8, 3),
  'line': 5683,
  'phase_list_mesh': 31,
  'phase_list_line': 5363,
  'pitch': 'Ana-2',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '81723', None, 0), (2, '8172563', None, 1))},
 {'mesh': 32,
  'net_span': (8, 4),
  'line': 5690,
  'phase_list_mesh': 32,
  'phase_list_line': 5364,
  'pitch': 'Ana-3',
  'class': 'Cyclic Chronodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': ('Sink',),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '418', None, 0), (2, '4518', 'Mn', 0), (3, '817254', 'Mj', 0))},
 {'mesh': 33,
  'net_span': (8, 5),
  'line': 5698,
  'phase_list_mesh': 33,
  'phase_list_line': 5365,
  'pitch': 'Cth-5',
  'class': 'Cyclic Chronodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': ('Sink',),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '5418', 'Mn', 1), (2, '81725', 'Mj', 0))},
 {'mesh': 34,
  'net_span': (8, 6),
  'line': 5706,
  'phase_list_mesh': 34,
  'phase_list_line': 5366,
  'pitch': 'Cth-4',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '817236', None, 1), (2, '817256', None, 0))},
 {'mesh': 35,
  'net_span': (8, 7),
  'line': 5712,
  'phase_list_mesh': 35,
  'phase_list_line': 5367,
  'pitch': 'Cth-3',
  'class': 'Cyclic Chronodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': ('Surge',),
  'shadows': (),
  'door': False,
  'phase_limit': True,
  'decademon': None,
  'rites': ((1, '718', None, 0), (2, '725418', 'Mn', 1), (3, '817', 'Mj', 0))},
 {'mesh': 36,
  'net_span': (9, 0),
  'line': 5721,
  'phase_list_mesh': 36,
  'phase_list_line': 5451,
  'pitch': 'Null',
  'class': 'Syzygetic Xenodemon',
  'clicks': (36,),
  'ciphers': (),
  'haunts': (45,),
  'feeds': ('Plex',),
  'prowls': ('Plex',),
  'shadows': (),
  'door': True,
  'phase_limit': False,
  'decademon': None,
  'rites': ((0, 'X', None, 0),)},
 {'mesh': 37,
  'net_span': (9, 1),
  'line': 5726,
  'phase_list_mesh': 37,
  'phase_list_line': 5452,
  'pitch': 'Ana-1',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': 4,
  'rites': ((1, '189', None, 0),)},
 {'mesh': 38,
  'net_span': (9, 2),
  'line': 5732,
  'phase_list_mesh': 38,
  'phase_list_line': 5453,
  'pitch': 'Ana-2',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '27189', None, 0), (2, '2754189', None, 1))},
 {'mesh': 39,
  'net_span': (9, 3),
  'line': 5738,
  'phase_list_mesh': 39,
  'phase_list_line': 5454,
  'pitch': 'Ana-3',
  'class': 'Chaotic Xenodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((0, '?', None, 0),)},
 {'mesh': 40,
  'net_span': (9, 4),
  'line': 5743,
  'phase_list_mesh': 40,
  'phase_list_line': 5455,
  'pitch': 'Ana-4',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '4189', None, 0), (2, '45189', None, 0))},
 {'mesh': 41,
  'net_span': (9, 5),
  'line': 5749,
  'phase_list_mesh': 41,
  'phase_list_line': 5456,
  'pitch': 'Cth-4',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '54189', None, 1),)},
 {'mesh': 42,
  'net_span': (9, 6),
  'line': 5755,
  'phase_list_mesh': 42,
  'phase_list_line': 5457,
  'pitch': 'Cth-3',
  'class': 'Chaotic Xenodemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((0, '?', None, 0),)},
 {'mesh': 43,
  'net_span': (9, 7),
  'line': 5759,
  'phase_list_mesh': 43,
  'phase_list_line': 5458,
  'pitch': 'Cth-2',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': False,
  'decademon': None,
  'rites': ((1, '7189', None, 0), (2, '7254189', None, 1))},
 {'mesh': 44,
  'net_span': (9, 8),
  'line': 5766,
  'phase_list_mesh': 44,
  'phase_list_line': 5459,
  'pitch': 'Cth-1',
  'class': 'Amphidemon',
  'clicks': (),
  'ciphers': (),
  'haunts': (36,),
  'feeds': (),
  'prowls': (),
  'shadows': (),
  'door': False,
  'phase_limit': True,
  'decademon': None,
  'rites': ((0, '89', None, 0),)})

# Zone system notes. Channel termini are given in the book as gate ordinals
# ('the 1st, 4th, and 7th'): ordinal n is the gate of Zone-n.
ZONE_NOTES = {
    0: {"line": 4687, "region": "PLEX", "region_ordinal": 1, "twin": 9, "tractor_of": None,
        "termini_ordinals": (0,), "phase_population": None, "mesh_tag": 0, "mesh_tag_line": 4699},
    1: {"line": 4759, "region": "TIME_CIRCUIT", "region_ordinal": 1, "twin": 8, "tractor_of": "Sink",
        "termini_ordinals": (1, 4, 7), "phase_population": 2, "phase_line": 4762,
        "mesh_tag": 1, "mesh_tag_line": 4774},
    2: {"line": 4846, "region": "TIME_CIRCUIT", "region_ordinal": 2, "twin": 7, "tractor_of": None,
        "termini_ordinals": None, "phase_population": 4, "phase_line": 4848,
        "mesh_tag": 3, "mesh_tag_line": 4856},
    3: {"line": 4929, "region": "WARP", "region_ordinal": 1, "twin": 6, "tractor_of": "Warp",
        "termini_ordinals": (2, 6), "phase_population": 8, "phase_line": 4933,
        "mesh_tag": 7, "mesh_tag_line": 4942},
    4: {"line": 5010, "region": "TIME_CIRCUIT", "region_ordinal": 3, "twin": 5, "tractor_of": None,
        "termini_ordinals": None, "phase_population": 16, "phase_line": 5012,
        "mesh_tag": 15, "mesh_tag_line": 5024},
    5: {"line": 5093, "region": "TIME_CIRCUIT", "region_ordinal": 6, "twin": 4, "tractor_of": "Hold",
        "termini_ordinals": None, "phase_population": 32, "phase_line": 5097,
        "mesh_tag": 31, "mesh_tag_line": 5105},
    6: {"line": 5173, "region": "WARP", "region_ordinal": 2, "twin": 3, "tractor_of": None,
        "termini_ordinals": (3, 5), "phase_population": 64, "phase_line": 5177,
        "mesh_tag": 63, "mesh_tag_line": 5186},
    7: {"line": 5256, "region": "TIME_CIRCUIT", "region_ordinal": 5, "twin": 2, "tractor_of": "Surge",
        "termini_ordinals": None, "phase_population": 128, "phase_line": 5259,
        "mesh_tag": 127, "mesh_tag_line": 5265},
    8: {"line": 5330, "region": "TIME_CIRCUIT", "region_ordinal": 4, "twin": 1, "tractor_of": None,
        "termini_ordinals": None, "phase_population": 256, "phase_line": 5333,
        "mesh_tag": 255, "mesh_tag_line": 5348},
    9: {"line": 5423, "region": "PLEX", "region_ordinal": 2, "twin": 0, "tractor_of": "Plex",
        "termini_ordinals": (8, 9), "phase_population": 512, "phase_line": 5428,
        "mesh_tag": 511, "mesh_tag_line": 5442},
}

GATE_NOTES = {
    0:  {"line": 4693, "source": 0, "target": 0, "disputed": True,
         "text": "The Zeroth Gate (Gt-00) seems to connect Zone-0 to itself ... its ultimate reality "
                 "is fundamentally disputed. Many versions of the Numogram delete it entirely."},
    1:  {"line": 4768, "source": 1, "target": 1, "text": "The First Gate (Gt-01) connects Zone-1 to itself"},
    3:  {"line": 4852, "source": 2, "target": 3, "from_region": "TIME_CIRCUIT", "to_region": "WARP",
         "consolidated_to": 3,
         "text": "The Second Gate (Gt-3) connects Zone-2 to Zone-3 ... line of escape from the Torque to "
                 "the Warp ... multiply consolidated by cumulation, prime-ordination, and mesh-tagging."},
    6:  {"line": 4936, "source": 3, "target": 6, "text": "The Third Gate (Gt-6) twists Zone-3 through Zone-6"},
    10: {"line": 5018, "source": 4, "target": 1, "orientation": "pro", "sole_orientation": True,
         "text": "The Fourth Gate (Gt-10) feeds Zone-4 forward to Zone-1 ... the only pro-cyclic "
                 "channel within the Torque."},
    15: {"line": 5103, "source": 5, "target": 6, "to_region": "WARP",
         "text": "The Fifth Gate (Gt-15) connects Zone-5 to Zone-6 ... abductions into the Warp."},
    21: {"line": 5182, "source": 6, "target": 3, "text": "The Sixth Gate (Gt-21) twists Zone-6 through Zone-3"},
    28: {"line": 5261, "source": 7, "target": 1, "orientation": "counter", "sole_orientation": True,
         "text": "The Seventh Gate (Gt-28) feeds Zone-7 back to Zone-1 ... the only counter-cyclic "
                 "path within the Torque."},
    36: {"line": 5337, "source": 8, "target": 9, "sole_tc_to_plex": True,
         "text": "The Eighth Gate (Gt-36) connects Zone-8 to Zone-9 ... the sole path of escape from "
                 "the Torque - or 'Time-Circuit' - into the Plex."},
    45: {"line": 5432, "source": 9, "target": 9, "involutionary_count": 3,
         "text": "The Ninth Gate (Gt-45) connects Zone-9 to itself, transducing the third "
                 "involutionary channel (see Zone-0, Zone-1)."},
}

SYSTEM = {
    "line": 4484,
    "zones": 10, "syzygies": 5, "demons": 45, "mesh_range": (0, 44),
    "pitch_extremes": ("Ana-7", "Cth-7"), "syzygetic_pitch": "Null",
    "time_circuit_syzygies": ((8, 1), (7, 2), (5, 4)),
    "upper_loop": "WARP", "lower_loop": "PLEX",
    "binary_cycle": (1, 2, 4, 8, 7, 5),
    "binary_cycle_line": 5799,            # 'Pandemonium Commentary, Two. Numogram and I Ching'
    "time_systems_line": 4496,
}

GLOSSARY_COUNTS = {
    "amphidemons": {"line": 7031, "count": 24, "warping": 12, "plexing": 12},
    "chronodemons": {"line": 7091, "count": 15, "syzygetic": 3, "cyclic": 12},
    "chaotic_xenodemons": {"line": 7088, "count": 4, "trackless": True},
    "decademons": {"line": 7138, "count": 4, "net_span_sum": 10},
    "imps": {"line": 7184, "count": 120, "doors_have_imps": False},
    "pitch_tones": {"line": 7268, "count": 15},
    "current_names": {"lines": (7170, 7270, 7303, 7313, 7364),
                      "names": {(7, 2): "Hold", (9, 0): "Plex", (5, 4): "Sink",
                                (8, 1): "Surge", (6, 3): "Warp"}},
    "time_circuit_currents": {"line": 7340, "names": ("Surge", "Hold", "Sink")},
}

DETAILED = {
    "lurgo": {
        "net_span": (1, 0),
        "paths": {"line": 6016, "count": 1, "routes": ("1890",)},
        "nests": {"line": 6045, "net_spans": ((8, 0), (8, 1), (9, 0), (9, 1), (9, 8))},
        "net_span_clicks_gate": {"line": 5996, "gate": 10},
        "mesh_clicks_gate": {"line": 6005, "gate": 0},
        "sarkon_tag": {"line": 6007, "value": 2},
        "imps_hosted": {"line": 6011, "value": 0},
        "pitch": {"line": 6010, "value": "Ana-1"},
    },
    "katak": {
        "net_span": (5, 4),
        "paths": {"line": 6111, "count": 2, "routes": ("54", "418725"),
                  "kinds": ("syzygetic", "minor")},
        "sole_syzygetic_phase_limit": {"line": 6086},
        "sole_syzygetic_with_nonsyzygetic_rite": {"line": 6121},
        "nonsyzygetic_rite_encircles_time_circuit": {"line": 6122},
        "ciphers_gate": {"line": 6088, "gate": 45},
        "mesh_ciphers_net_span": {"line": 6091, "net_span": (4, 1), "mesh_of_that_demon": 7},
        "sarkon_tag": {"line": 6097, "value": 47},
        "imps_hosted": {"line": 6104, "value": 10},
        "feeds": {"line": 6106, "current": "Sink"},
    },
}

_NAMES = {(1, 0): {'name': 'Lurgo',
          'matrix_header': 'Lurgo (Legba). (Terminal) Initiator.',
          'phase_list_name': 'Lurgo'},
 (2, 0): {'name': 'Duoddod',
          'matrix_header': 'Duoddod. Duplicitous Redoubler.',
          'phase_list_name': 'Duoddod'},
 (2, 1): {'name': 'Doogu',
          'matrix_header': 'Doogu (The Blob). Original-Schism.',
          'phase_list_name': 'Doogu'},
 (3, 0): {'name': 'Ixix', 'matrix_header': 'Ixix (Yix). Abductor.', 'phase_list_name': 'Ixix'},
 (3, 1): {'name': 'Ixigool',
          'matrix_header': 'Ixigool (Djinn of the Magi).',
          'phase_list_name': 'Ixigool'},
 (3, 2): {'name': 'Ixidod',
          'matrix_header': 'Ixidod (King Sid). The Zombie-Maker.',
          'phase_list_name': 'Ixidod'},
 (4, 0): {'name': 'Krako',
          'matrix_header': 'Krako (Kru, Karak-oa). The Croaking Curse.',
          'phase_list_name': 'Krako'},
 (4, 1): {'name': 'Sukugool',
          'matrix_header': 'Sukugool (Old Skug). The Sucking-Ghoul.',
          'phase_list_name': 'Sukugool'},
 (4, 2): {'name': 'Skoodu',
          'matrix_header': "Skoodu (Li'l Scud). The Fashioner.",
          'phase_list_name': 'Skoodu'},
 (4, 3): {'name': 'Skarkix',
          'matrix_header': 'Skarkix (Sharky, Scar-head). Buzz-Cutter.',
          'phase_list_name': 'Skarkix'},
 (5, 0): {'name': 'Tokhatto',
          'matrix_header': 'Tokhatto (Old Toker, Top Cat). Decimal Camouflage.',
          'phase_list_name': 'Tokhatto'},
 (5, 1): {'name': 'Tukkamu',
          'matrix_header': 'Tukkamu. Occulturation.',
          'phase_list_name': 'Tukkamu'},
 (5, 2): {'name': 'Kuttadid',
          'matrix_header': 'Kuttadid (Kitty). Ticking Machines.',
          'phase_list_name': 'Kuttadid'},
 (5, 3): {'name': 'Tikkitix',
          'matrix_header': 'Tikkitix (Tickler). Clicking Menaces.',
          'phase_list_name': 'Tikkitix'},
 (5, 4): {'name': 'Katak', 'matrix_header': 'Katak. Desolator.', 'phase_list_name': 'Katak'},
 (6, 0): {'name': 'Tchu',
          'matrix_header': 'Tchu (Tchanul). Source of Subnothingness.',
          'phase_list_name': 'Tchu'},
 (6, 1): {'name': 'Djungo', 'matrix_header': 'Djungo. Infiltrator.', 'phase_list_name': 'Djungo'},
 (6, 2): {'name': 'Djuddha',
          'matrix_header': 'Djuddha (Judd Dread). Decentred Threat.',
          'phase_list_name': 'Djuddha'},
 (6, 3): {'name': 'Djynxx',
          'matrix_header': 'Djynxx (Ching, The Jinn). Child Stealer.',
          'phase_list_name': 'Djynxx'},
 (6, 4): {'name': 'Tchakki',
          'matrix_header': 'Tchakki (Chuckles). Bag of Tricks.',
          'phase_list_name': 'Tchakki'},
 (6, 5): {'name': 'Tchattuk',
          'matrix_header': 'Tchattuk (One Eyed Jack, Djatka). Pseudo-Basis.',
          'phase_list_name': 'Tchattuk'},
 (7, 0): {'name': 'Puppo',
          'matrix_header': 'Puppo (The Pup). Break-Outs.',
          'phase_list_name': 'Puppo'},
 (7, 1): {'name': 'Bubbamu',
          'matrix_header': 'Bubbamu (Bubs). After Babylon.',
          'phase_list_name': 'Bubbamu'},
 (7, 2): {'name': 'Oddubb',
          'matrix_header': 'Oddubb (Odba). Broken Mirror.',
          'phase_list_name': 'Oddubb'},
 (7, 3): {'name': 'Pabbakis',
          'matrix_header': 'Pabbakis (Pabzix). Dabbler.',
          'phase_list_name': 'Pabbakis'},
 (7, 4): {'name': 'Ababbatok',
          'matrix_header': 'Ababbatok (Abracadabra). Regenerator.',
          'phase_list_name': 'Ababbatok'},
 (7, 5): {'name': 'Papatakoo',
          'matrix_header': 'Papatakoo (Pataku) Upholder.',
          'phase_list_name': 'Papatakoo'},
 (7, 6): {'name': 'Bobobja',
          'matrix_header': 'Bobobja (Bubbles, Beelzebub (Lord of the Flies)). Heavy Atmosphere.',
          'phase_list_name': 'Bobobja'},
 (8, 0): {'name': 'Minommo', 'matrix_header': 'Minommo. Webmaker.', 'phase_list_name': 'Minommo'},
 (8, 1): {'name': 'Mur Mur',
          'matrix_header': 'Mur Mur (Murrumur, Mu(mu)). Dream-Serpent.',
          'phase_list_name': 'Murrumur'},
 (8, 2): {'name': 'Nammamad',
          'matrix_header': 'Nammamad. Mirroracle.',
          'phase_list_name': 'Nammamad'},
 (8, 3): {'name': 'Mummumix',
          'matrix_header': 'Mummumix (Mix-Up). The Mist-Crawler.',
          'phase_list_name': 'Mummumix'},
 (8, 4): {'name': 'Numko',
          'matrix_header': 'Numko (Old Nuk). Keeper of Old Terrors.',
          'phase_list_name': 'Numko'},
 (8, 5): {'name': 'Muntuk',
          'matrix_header': 'Muntuk (Manta, Manitou). Desert Swimmer.',
          'phase_list_name': 'Muntuk'},
 (8, 6): {'name': 'Mommoljo',
          'matrix_header': 'Mommoljo (Mama Jo). Alien Mother.',
          'phase_list_name': 'Mommoljo'},
 (8, 7): {'name': 'Mombbo',
          'matrix_header': 'Mombbo. Tentacle Face (Fishy-princess).',
          'phase_list_name': 'Mombbo'},
 (9, 0): {'name': 'Uttunul',
          'matrix_header': 'Uttunul. Seething Void.',
          'phase_list_name': 'Uttunul'},
 (9, 1): {'name': 'Tutagool',
          'matrix_header': 'Tutagool (Yettuk). The Tattered Ghoul.',
          'phase_list_name': 'Tuttagool'},
 (9, 2): {'name': 'Unnunddo',
          'matrix_header': 'Unnunddo (The False Nun). Double-Undoing.',
          'phase_list_name': 'Unnunddo'},
 (9, 3): {'name': 'Ununuttix',
          'matrix_header': 'Ununuttix (Tick-Tock). Particle Clocks.',
          'phase_list_name': 'Ununuttix'},
 (9, 4): {'name': 'Ununak',
          'matrix_header': 'Ununak (Nuke). Blind Catastrophe.',
          'phase_list_name': 'Unnunaka'},
 (9, 5): {'name': 'Tukutu',
          'matrix_header': 'Tukutu (Killer-Kate). Cosmotraumatics.',
          'phase_list_name': 'Tukutu'},
 (9, 6): {'name': 'Unnutchi',
          'matrix_header': "Unnutchi (Outch, T'ai Chi). Tachyonic immobility (slow vortex).",
          'phase_list_name': 'Unnutchi'},
 (9, 7): {'name': 'Nuttubab',
          'matrix_header': 'Nuttubab (Nut-Cracker). Mimetic Anorganism.',
          'phase_list_name': 'Nuttubab'},
 (9, 8): {'name': 'Ummnu',
          'matrix_header': 'Ummnu (Om, Omni, Amen, Omen). Ultimate Inconsequence.',
          'phase_list_name': 'Ummnu'}}


class BlindingError(RuntimeError):
    pass


def demon_names(unblind: bool = False):
    """Names are withheld unless explicitly unblinded. Survey, clustering and agency
    code must never pass unblind=True; only the Stage VII comparison, after the
    ingression map is sealed."""
    if not unblind:
        raise BlindingError("demon names are blinded; pass unblind=True only in Stage VII")
    return dict(_NAMES)
